name = "4byte-dictionary"
main = "src/index.js"
compatibility_date = "2023-01-06"
usage_model = "bundled"

kv_namespaces = [
    { binding = "NAMESPACE", id = "98710681c26249528ed99877c100538a", preview_id = "3cd38e4fff554584b86fc9007d5fe292" }
]

[env.production]
vars = { ENVIRONMENT = "production" }
name = "service-cloudflare-4bytes-proxy"
kv_namespaces = [
    { binding = "NAMESPACE", id = "4e3c5989d8ac4c68a90d095edd770b15" }
]
routes = [
	{ pattern = "4bytesdictionary.universalprofile.cloud", custom_domain = true },
]

[triggers]
crons = [ ]
